### ISSUE TITLE
Unable to rename … file exists

### ISSUE THREAD

**Issue by frebro** [75lb/renamer-case#1]
I'm unable to run this from the command line:

```bash
❯ ./node_modules/.bin/renamer -d -p case --case kebab svg/*.svg
Dry run
✔︎ svg/Alert-30.svg → svg/alert-30.svg 
Unable to rename svg/Alert-30.svg to svg/alert-30.svg [file exists]
```

The script stops on the first file, claiming it can't be renamed because the file already exists. I'm on macOS 10.15.

**Comment by 75lb** [comment]
macOS is case insensitive, see here:
https://github.com/75lb/renamer/wiki/How-to-change-the-case-of-a-file-on-a-case-insensitive-OS

**Comment by frebro** [comment]
Ah! I knew that, but actually thought renamer would handle that for me. Using `--force` makes sense though. Thanks for fast reply!
